name: Deploy to Skytap VM

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm ci

    - name: Build Next.js app
      run: npm run build

    - name: Prepare deployment package
      run: |
        mkdir deploy
        cp -r .next public package.json ecosystem.config.js deploy/
        cp -r node_modules deploy/node_modules

    - name: Debug - List deploy files
      run: ls -Rla deploy

    - name: Copy files to Skytap VM
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.VM_PORT }}
        source: "deploy"
        target: ${{ secrets.DEPLOY_DIR }}
        strip_components: 0
        rm: false
        overwrite: true

    - name: SSH and Restart PM2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        port: ${{ secrets.VM_PORT }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          cd ${{ secrets.DEPLOY_DIR }}
          pm2 delete testing_project || true
          pm2 start ecosystem.config.js
